# Generated by Django 2.2.2 on 2019-06-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190610_0546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
