# Generated by Django 2.2.2 on 2019-06-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_on', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('status', models.CharField(default='IN PROGRESS', max_length=2)),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TaskList')),
            ],
        ),
    ]
